### ISSUE TITLE
Why the new permission to read browser history?

### ISSUE THREAD

**Issue by Eisys** [ZusorCode/GoodTwitterChrome#1]
Title.

It worked before, without said permission...

**Comment by frozaum** [comment]
i want to know that too

**Comment by kwsch** [comment]
Judging from the [recent commit which added the new permission requirement](
https://github.com/ZusorCode/GoodTwitterChrome/commit/bf4f55def63ce4e081b75958566954fbccc13695#diff-4b1eb3dc48c4e16d49db5b42298fe654R10):

It's to facilitate a cleaner install (instant) by refreshing existing tabs and clearing any cached data that would prevent the addon from functioning perfectly when installed.

The addon code is harmless; see [background.js](https://github.com/ZusorCode/GoodTwitterChrome/blob/55d8d38084c033a404a1749bd79d0dcb27018e5c/background.js#L24-L30) to see what it does :)

**Comment by ZusorCode** [comment]
@kwsch is right, that's exactly what it does. Closed unless there's any other questions
