### ISSUE TITLE
So, did Twitter break this extension?

### ISSUE THREAD

**Issue by HereticWilson** [ZusorCode/GoodTwitterChrome#20]
It used to be that if I just refreshed the tab once, Twitter would revert back to the old layout with this  extension kicking in. That no longer seems to be the case. Have they closed whatever loophole was being used?

**Comment by Jertzukka** [comment]
Works for me.

**Comment by ZusorCode** [comment]
See if anything here fixes it: https://github.com/ZusorCode/GoodTwitterChrome/blob/master/troubleshooting.md
