### ISSUE TITLE
no profile picture on "Following" and "Followers" pages, nor on popup when hovering over name

### ISSUE THREAD

**Issue by felishogis** [ZusorCode/GoodTwitterChrome#23]
![,1a](https://user-images.githubusercontent.com/56051563/66005127-27fef080-e470-11e9-9018-c377ff7bf8bf.png)
![,2b](https://user-images.githubusercontent.com/56051563/66005130-2af9e100-e470-11e9-9590-c4b9b9c5a79a.png)
![,3c](https://user-images.githubusercontent.com/56051563/66005343-c9864200-e470-11e9-92df-a7b6c722fa83.png)
As stated in the title, these pages do not show the icons of the profiles. I have attached some examples of the issue. I do not know whether this is a bug or if it was simply deemed unnecessary, but these _are_ available on mobile Twitter.

**Comment by ZusorCode** [comment]
Is this still happening? Doesn't seem to happen for me.
