### ISSUE TITLE
Suddenly Back to New Twitter.

### ISSUE THREAD

**Issue by 88Unknown88** [ZusorCode/GoodTwitterChrome#24]
Happened today.
No idea why it might have happened, didn't do anything out of the normal.
On up to date chrome version.

**Comment by ZusorCode** [comment]
Try the troubleshooting guide: https://github.com/ZusorCode/GoodTwitterChrome/blob/master/troubleshooting.md

**Comment by WinterStar96** [comment]
Having the same issue. Tried all the stuff on the troubleshooting page and nothing worked for me.
Though after clearing my cookies, it looks like if you're not logged in, it works and changes it to the old Twitter but as soon as you log in, it becomes the new Twitter. They probably changed something up again.

**Comment by ZusorCode** [comment]
I'm rolling back GoodTwitter to version 1.3 right now (it will appear as version 1.5). Let me know if that fixes it. A lot of people are reporting this issue and I'm looking into this.

**Comment by WinterStar96** [comment]
After removing from Chrome and then installing it again, also pressed Ctrl+F5 to force refresh, it seems everything is back to normal.

**Comment by oneblankspace** [comment]
I had a similar problem.  I was able to update to the version called 1.5 in Chrome, but I had to deactivate it in Opera to update.

**Comment by ZusorCode** [comment]
There's a beta version of GoodTwitter that should fix this. Try this https://chrome.google.com/webstore/detail/goodtwitter-beta/ehjbcokpmfbmpjlldihlcbkoakikcomd after uninstalling regular GoodTwitter first.
