### ISSUE TITLE
Clicking tweet goes straight to profile?

### ISSUE THREAD

**Issue by Finnicklmao** [ZusorCode/GoodTwitterChrome#25]
Title explains it

I click onto any tweet, and it goes to the OP's profile and I'd rather not keep clicking back arrow to keep going to home

**Comment by jayrosennyu** [comment]
This started about a week ago. On the website, twitter.com, If you click on a quoted tweet, you go straight to the profile of the user who posted the original. It used to open the quoted tweet in a box, and when you clicked away from it you were still on your timeline. Now you have use the arrow to return to you timeline and you are not in the same place that you were before.

**Comment by Jacklekins** [comment]
I have the same problem. Any tweet I click takes me directly to the person's profile. Started happening today for me.

**Comment by Poopooracoocoo** [comment]
this drives me insane because it makes browsing Twitter slow. The whole reason I like GoodTwitter/old Twitter is because I can browse quickly

**Comment by ZusorCode** [comment]
Sorry for not replying, try the goodtwitter beta https://chrome.google.com/webstore/detail/goodtwitter-beta/ehjbcokpmfbmpjlldihlcbkoakikcomd
