### ISSUE TITLE
Clicking on  tweets will send you straight to the persons profile

### ISSUE THREAD

**Issue by H20Heavy** [ZusorCode/GoodTwitterChrome#29]
as stated by the title, the tweets i click sends me straight to the persons profile instead of just reading the persons tweet, had this issue today, did the small fixes like log out and back in, uninstall and reinstall the chrome extension, and deleted the cache. It still doesn't work properly. I am on the latest chrome browser and on windows 10 latest version of windows 10.

**Comment by YoshAye** [comment]
I am having the same problem today now that I got the newer Google Chrome update.

**Comment by H20Heavy** [comment]
Wasn't aware that there was a chrome update, that might be the issue, hoping it gets resolved cause idk if we can revert back to an old version of chrome 🤷

**Comment by ZusorCode** [comment]
Try the goodtwitter beta https://chrome.google.com/webstore/detail/goodtwitter-beta/ehjbcokpmfbmpjlldihlcbkoakikcomd
