### ISSUE TITLE
Maximum "displayed tweet limit"

### ISSUE THREAD

**Issue by TheBluestCrowe** [ZusorCode/GoodTwitterChrome#3]
Hey. New to this extension today.

I noticed if you scroll down there is a maximum amount of tweets that will load on the news feed - until you get the "back to top" message at the bottom of the feed.

https://youtu.be/GDJDf8H_GIg

It seems to refresh once and only once.
I may have got it to add a few more a second time but that was after waiting a few minutes and it could only scroll down ever so slightly more etc.

This is without any additional twitter extensions installed (ad-block turned off).

If there's more information needed I'm happy to add to it.
Using Chrome, Windows 10.

**Comment by ZusorCode** [comment]
When I tried it, the same thing happened but the tweets just loaded once i scrolled down a bit more. Can you try that

**Comment by TheBluestCrowe** [comment]
I have and it doesnt do anything. It loads once and not beyond that.

**Comment by TheBluestCrowe** [comment]
Okay I realise probably nothing has changed but as of right now I'm no longer getting this issue. Sorry to be a bother.

**Comment by fireattack** [comment]
I still get this frequently.
