### ISSUE TITLE
Tried the usual stuff But clicking on tweets still sends it to a person's profile

### ISSUE THREAD

**Issue by BloodyOranges** [ZusorCode/GoodTwitterChrome#30]
For 2 days everytime i click on a person's tweet it sends me back to their profile and it's very annoying i've tried most things like logging off and back on /cleaning up search history/removing cookies/restarting computer but it still stays like this sometimes i am able to click on a person's tweet without the thing but when i go to their profile or my own it does the thing again and my google chrome is up to date Does anyone know what to do? if not i really hope this issue will be fixed

**Comment by ZusorCode** [comment]
Try the goodtwitter beta https://chrome.google.com/webstore/detail/goodtwitter-beta/ehjbcokpmfbmpjlldihlcbkoakikcomd
