### ISSUE TITLE
You’re currently using an unsupported browser — for the best Twitter experience, please consider updating to Windows 10, or check the list of supported browsers.

### ISSUE THREAD

**Issue by subsoap** [ZusorCode/GoodTwitterChrome#46]
New banner which appears when this extension is used. The end is near. 😭

**Comment by GitHubNme** [comment]
Ditto

**Comment by jbmillman** [comment]
![Screenshot 2020-02-19 at 1 06 43 PM](https://user-images.githubusercontent.com/61247215/74861715-ce149f80-5318-11ea-9723-6cecff4e2d7b.png)

**Comment by TheSimArchitect** [comment]
Same here, sad! New Twitter interface is bad, can't translate tweets on the fly etc.

**Comment by kittuar** [comment]
ugh, same here. I wish twitter would lay off trying to get everyone to update, it's obvious that people don't like what they're doing with all this, so just leave us alone! it's not hurting anyone.

**Comment by myriam** [comment]
Ditto.

**Comment by TheSimArchitect** [comment]
They probably make more money with ads on the new interface.

**Comment by Lasharus** [comment]
Same here, sadly. Shame, I still vastly prefer this UI. :(

**Comment by cypheroftyr** [comment]
Me fourth, or whatever number we're on.

**Comment by moriiyanis** [comment]
I've got the same issue. I've temporarily blocked that page 'element' using AdGuard, so I don't have to see it at least, doesn't seem to hider functionality. I definitely do not want to stop using the extension, the new layout gives me an aneurysm.

**Comment by RHUNYADY** [comment]
Same issue here

**Comment by mackief3000** [comment]
add this for adblock plus and ublock twitter.com##.Banner--aboveNav.Banner

**Comment by christianboyle** [comment]
It's also possible to keep using the extension in conjunction with the [Stylus extension](https://add0n.com/stylus.html) that lets you write custom CSS rules.

`
#banners { display: none; }
`
`
.topbar-spacer { padding-top: 47px !important; }
`

**Comment by RHUNYADY** [comment]
> I've got the same issue. I've temporarily blocked that page 'element' using AdGuard, so I don't have to see it at least, doesn't seem to hinder functionality. I definitely do not want to stop using the extension, the new layout gives me an aneurysm.
> 
> If you use AdGuard, you can add the following line to the "User Rules" in the menu to block the message. It leaves a little gap between the nav menu and the rest of the page, but it's better than the other nonsense.
> 
> `twitter.com###banners > div.Banner.Banner--aboveNav`

This worked! :-)

**Comment by honkfathermax** [comment]
> It's also possible to keep using the extension in conjunction with the [Stylus extension](https://add0n.com/stylus.html) that lets you write custom CSS rules.
> 
> `#banners { display: none; }`
> `.topbar-spacer { padding-top: 47px !important; }`

Thanks a lot, this works perfectly!

**Comment by TheSimArchitect** [comment]
True, the method works, you can even use the zapper from uBlock or a similar tool. What worries is the fact Twitter might just stop working completely in a few days for people like "us"...

**Comment by ZusorCode** [comment]
Fixed in 0fc87aa881315cc7f6cb1022a7130d9a22668b2f
