### ISSUE TITLE
Twitter says I'm using an unsupported browser even after updating Chrome

### ISSUE THREAD

**Issue by miraclesports** [ZusorCode/GoodTwitterChrome#48]
I'm on Good Twitter Beta. I get a message on the top of the screen that tells me I'm using an unsupported browser, and the message will not go away, sticking there even as I try to scroll through. Chrome is updated, so I'm not sure what the issue is. After I updated Chrome and it took me to Bad Twitter, I didn't get that message. It only came when I went to the Good Twitter page.

![Screen Shot 2020-02-19 at 3 15 14 PM](https://user-images.githubusercontent.com/61251141/74872159-aaf2eb80-532a-11ea-8d0f-678ccf11e811.png)

**Comment by adamzea** [comment]
Same here. I assume it's because Good Twitter pretends to be an older browser that doesn't work with Bad Twitter thus tricking Bad Twitter into switching to Good Twitter. Bad Twitter must have caught on and is trying to get us to switch to Bad Twitter.

**Comment by Zephmarie** [comment]
Same. But using most recent Firefox. Maybe Good Twitter needs an update?

**Comment by GitHubNme** [comment]
Same.

**Comment by Xuleos** [comment]
This issue was fixed for me in the latest commit. You can fix it by downloading the Good Twitter repository yourself and loading it unpacked
![image](https://user-images.githubusercontent.com/37721396/74880993-7850ef00-533a-11ea-9965-4bb1d1cb760c.png)

**Comment by Zephmarie** [comment]
Where does one fine the Good Twitter repository?

**Comment by svenrenhoek** [comment]
> Where does one fine the Good Twitter repository?

https://chrome.google.com/webstore/detail/goodtwitter/jbanhionoclikdjnjlcmefiofgjimgca

**Comment by Zephmarie** [comment]
Oh, sorry. I'm in wrong thread. Using latest version Firefox. Thanks for the reply, though.

**Comment by Xuleos** [comment]
> > Where does one fine the Good Twitter repository?
> 
> https://chrome.google.com/webstore/detail/goodtwitter/jbanhionoclikdjnjlcmefiofgjimgca

Right here! This is the repository:
https://github.com/ZusorCode/GoodTwitterChrome

**Comment by Zephmarie** [comment]
> 
> 
> > > Where does one fine the Good Twitter repository?
> > 
> > 
> > https://chrome.google.com/webstore/detail/goodtwitter/jbanhionoclikdjnjlcmefiofgjimgca
> 
> Right here! This is the repository:
> https://github.com/ZusorCode/GoodTwitterChrome

Wouldn't happen to know how to fix it in Firefox would you? I don't get the unsupported browser warning in Chrome for some reason.

**Comment by ZusorCode** [comment]
The updated add-on is live on the stores
