### ISSUE TITLE
Help! Saying "Browser is not supported" 

### ISSUE THREAD

**Issue by RealDylanVolk** [ZusorCode/GoodTwitterChrome#49]
My Google Chrome is updated to the latest version, and this is what I am seeing on top of Twitter while using GoodTwitter. Can anybody help?
 
![Screen Shot 2020-02-19 at 12 12 01 PM](https://user-images.githubusercontent.com/61252005/74874338-a839cb80-5315-11ea-84f8-a6b04e8df04f.png)

**Comment by iammanpreetsingh** [comment]
I am facing this same issue

**Comment by Zephmarie** [comment]
Same issue, but using latest Firefox. Bad Twitter must be aware of Good Twitter and trying to make us switch. Won't do it.

**Comment by svenrenhoek** [comment]
I fixed it by updating Chrome browser to Version 80.0.3987.116 (Official Build) (64-bit)

**Comment by ZusorCode** [comment]
The newest addon update fixes this

**Comment by Zephmarie** [comment]
Fixed! Thank you!
