### ISSUE TITLE
Twitter dark mode not working

### ISSUE THREAD

**Issue by theagmggg** [ZusorCode/GoodTwitterChrome#6]
When using dark mode on twitter the sides turn don't have the dark mode colors when scrolling down.
![Screenshot at Aug 06 01-17-08](https://user-images.githubusercontent.com/53809815/62515443-f955f800-b7e7-11e9-8220-daed94e6bcac.png)

**Comment by filipre** [comment]
It works fine for me. Maybe try out the solution from #5 ? Or try it out in an Incognito window. Which browser do you use?
